### ISSUE TITLE
Checkbox not showing in all email accounts

### ISSUE THREAD

**Issue by MattR658** [umount/rcplugin_chbox#6]
I am running Roundcube 0.9.5 with 37 email accounts. Certain accounts have the checkbox showing up on their account while others do not. I am not sure why this is happening because they are all using the same skin (Larry).

**Comment by 6ec123321** [comment]
Tested and Fixed for Roundcubemail-1.1.0 and 1.0.3

https://github.com/6ec123321/chbox/tree/0.2.4
or
https://github.com/6ec123321/rcplugin_chbox/tree/patch-2
